<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16654" started-at="2017-07-27T21:31:45Z" finished-at="2017-07-27T21:32:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16654" started-at="2017-07-27T21:31:45Z" finished-at="2017-07-27T21:32:02Z">
      <class name="com.test.sqs.ExceptionsTest">
        <test-method status="PASS" signature="testSetUp()[pri:0, instance:com.test.sqs.ExceptionsTest@5442a311]" name="testSetUp" is-config="true" duration-ms="11106" started-at="2017-07-27T22:31:45Z" finished-at="2017-07-27T22:31:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.sqs.ExceptionsTest@5442a311]" name="setUp" is-config="true" duration-ms="5292" started-at="2017-07-27T22:31:57Z" finished-at="2017-07-27T22:32:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="numberOfRowsExceedsTest()[pri:0, instance:com.test.sqs.ExceptionsTest@5442a311]" name="numberOfRowsExceedsTest" duration-ms="67" started-at="2017-07-27T22:32:02Z" finished-at="2017-07-27T22:32:02Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 11, Size: 10]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 11, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.test.sqs.ExceptionsTest.numberOfRowsExceedsTest(ExceptionsTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- numberOfRowsExceedsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.sqs.ExceptionsTest@5442a311]" name="tearDown" is-config="true" duration-ms="134" started-at="2017-07-27T22:32:02Z" finished-at="2017-07-27T22:32:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.sqs.ExceptionsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
